#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Border Color
bspc config focused_border_color "#F0C674"

#Autostart programs
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
